### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Marc-06** [fsaris/home-assistant-awox#11]
With the newest update b4cc41f I can not connect anymore to my eglo panel 120.
Here is the log :
2021-01-06 18:34:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-06 18:34:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-06 18:34:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for awox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-06 18:34:40 INFO (MainThread) [custom_components.awox] setup config flow entry {'mesh_name': '81a8cs7O', 'mesh_password': 'dea2c5fb', 'mesh_key': 'b8b8096b', 'devices': [{'mesh_id': 16618, 'name': 'EGLOPanel', 'mac': 'a4:c1:38:64:40:ea', 'model': True, 'manufacturer': True, 'firmware': True, 'hardware': True, 'type': '.ble.tlmesh.light.switch.color.white.dimming.temperature.', 'supported_features': 19}, {'mesh_id': 359, 'name': 'EGLORemote', 'mac': 'a4:c1:38:72:01:67', 'model': True, 'manufacturer': True, 'firmware': True, 'hardware': True, 'type': '.ble.tlmesh.sensor.rcu.'}]}
2021-01-06 18:34:50 DEBUG (MainThread) [custom_components.awox.light] entry [{'mesh_id': 16618, 'name': 'EGLOPanel', 'mac': 'a4:c1:38:64:40:ea', 'model': True, 'manufacturer': True, 'firmware': True, 'hardware': True, 'type': '.ble.tlmesh.light.switch.color.white.dimming.temperature.', 'supported_features': 19}, {'mesh_id': 359, 'name': 'EGLORemote', 'mac': 'a4:c1:38:72:01:67', 'model': True, 'manufacturer': True, 'firmware': True, 'hardware': True, 'type': '.ble.tlmesh.sensor.rcu.'}]
2021-01-06 18:34:50 INFO (MainThread) [custom_components.awox.awox_mesh] Registered [a4:c1:38:64:40:ea] 16618
2021-01-06 18:34:50 INFO (MainThread) [custom_components.awox.light] setup entry [16618] EGLOPanel
2021-01-06 18:34:50 INFO (MainThread) [custom_components.awox.awox_mesh] [a4:c1:38:64:40:ea][EGLOPanel] Trying to connect
2021-01-06 18:34:50 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform awox
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/awox/light.py", line 124, in device_info
"model": self._model.replace('_', ' '),
AttributeError: 'bool' object has no attribute 'replace'
2021-01-06 18:34:51 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned
2021-01-06 18:34:55 WARNING (MainThread) [custom_components.awox.awox_mesh] [a4:c1:38:64:40:ea][EGLOPanel] Timeout trying to connect, trying next device
2021-01-06 18:34:55 ERROR (MainThread) [custom_components.awox.awox_mesh] Error fetching awox data: No device connected
2021-01-06 18:34:55 DEBUG (MainThread) [custom_components.awox.awox_mesh] Finished fetching awox data in 5.877 seconds
2021-01-06 18:35:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/awox/light.py", line 124, in device_info
"model": self._model.replace('_', ' '),
AttributeError: 'bool' object has no attribute 'replace'
2021-01-06 18:35:54 ERROR (MainThread) [homeassistant.components.upnp] Timeout fetching ICOTERA router data
2021-01-06 18:36:09 ERROR (MainThread) [custom_components.hacs] custom-components/sensor.rpi_power - Repository is archived.

**Comment by fsaris** [comment]
@Marc-06 could you maybe remove the integration and re-add it again?

In one of the previous versions the device info was incorrect processed

**Comment by Marc-06** [comment]
Ok that 's it. Thanks afin for this great job.
