### ISSUE TITLE
AwoX mesh became unavailable

### ISSUE THREAD

**Issue by Aljumaili85** [fsaris/home-assistant-awox#117]
fresh installed home assistant ( OS 12.4 , Core 2024.7.3) 
HACS 1.34.0
AwoX MESH control  0.1.6
problem: The lights has been added successfully  but the  system always shows "AwoX mesh became unavailable" and lights are inactive to turn on/off  

```

2024-07-25 22:13:53.134 ERROR (Thread-32) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/pygatt/backends/gatttool/gatttool.py", line 140, in run
    clb(event)
  File "/usr/local/lib/python3.12/site-packages/pygatt/backends/gatttool/gatttool.py", line 550, in _handle_notification_string
    self._connected_device.receive_notification(handle, values)
  File "/usr/local/lib/python3.12/site-packages/pygatt/device.py", line 291, in receive_notification
    callback(handle, value)
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 348, in _handleNotification
    self._parseStatusResult(message)
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 410, in _parseStatusResult
    self.status_callback(status)
  File "/config/custom_components/awox/awox_mesh.py", line 202, in mesh_status_callback
    self._devices[status['mesh_id']]['callback'](status)
  File "/config/custom_components/awox/light.py", line 272, in status_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in async_write_ha_state
    report_non_thread_safe_operation("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'awox' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/awox/light.py, line 272: self.async_write_ha_state(). Please report it to the author of the 'awox' custom integration.
2024-07-25 22:13:55.390 INFO (MainThread) [custom_components.awox.awox_mesh] [5AgwanX7] Queue command requestStatus {'dest': 65535, 'withResponse': True}
2024-07-25 22:13:55.392 DEBUG (AwoxMeshCommands-5AgwanX7) [custom_components.awox.awox_mesh] [5AgwanX7] process 0/0 - {'command': 'requestStatus', 'params': {'dest': 65535, 'withResponse': True}, 'callback': <function AwoxMesh._async_add_command_to_queue.<locals>.command_executed at 0x7f6e445da0>, 'allow_to_fail': False}
2024-07-25 22:13:55.394 DEBUG (AwoxMeshCommands-5AgwanX7) [custom_components.awox.awoxmeshlight] [5AgwanX7][a4:c1:38:72:c0:1c] requestStatus(65535)
2024-07-25 22:13:55.397 INFO (AwoxMeshCommands-5AgwanX7) [custom_components.awox.awoxmeshlight] [5AgwanX7][a4:c1:38:72:c0:1c] Writing command 218 data b'\x10'`
```

**Comment by Aljumaili85** [comment]
I tried to instal,l manually, the previous version of AwoX (0.1.5) putting the awox folder inside the  custom_components folder but it seems that the current version of the integration is incompatibile . is there a way to install a specific integration version that is compatible with AwoX v0.1.5? thanks

**Comment by fsaris** [comment]
See https://github.com/fsaris/home-assistant-awox/issues/110 I suggest to switch to the esp32 alternative

**Comment by jaceneliot** [comment]
Hi. Is there any plan to fix it ? I succed to add the bulbs with the integration but i can't interact with them :/

**Comment by Aljumaili85** [comment]
@jaceneliot,not a real solution, I just downgrade my HA to an older version and its working just fine.

**Comment by jaceneliot** [comment]
> @jaceneliot,not a real solution, I just downgrade my HA to an older version and its working just fine.

Thanks ! Can I ask you which version ? Is it easy to downgrade without loosing data's  and settings ?

**Comment by Aljumaili85** [comment]
@jaceneliot  its always a good practice to keep a backup version before do any up/downgrade, my current system is:
OS 12.4 , Core 2023.12.1
you can use this command to install a specific version "ha core update --version 2023.12.1"
**BACKUP FIRST** :)

**Comment by jaceneliot** [comment]
Thanks. I'm gonna try that. Is that the last version Awox intergration works with ?

**Comment by Aljumaili85** [comment]
@jaceneliot give this version 0.1.4 a try .. Good luck
