### ISSUE TITLE
looks like it wants to kill the bluetooth

### ISSUE THREAD

**Issue by gstefanov** [fsaris/home-assistant-awox#21]
Hello,

I'm trying to run the integration on my rasp4, I have installed the bluetooth and lib of bluetooth as you said, turned the bluetooth service on, added the bulbs inside the HA and I get this error, familiar to you?

`021-02-08 19:59:21 ERROR (MainThread) [custom_components.awox.scanner] Failed: Command 'PATH=/usr/sbin:$PATH; rfkill unblock bluetooth' returned non-zero exit status 1.
Traceback (most recent call last):
File "/config/custom_components/awox/scanner.py", line 38, in async_find_devices
bl = await hass.async_add_executor_job(init)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/awox/scanner.py", line 34, in init
return Bluetoothctl()
File "/config/custom_components/awox/bluetoothctl.py", line 19, in __init__
subprocess.check_output("PATH=/usr/sbin:$PATH; rfkill unblock bluetooth", shell=True)
File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'PATH=/usr/sbin:$PATH; rfkill unblock bluetooth' returned non-zero exit status 1.
2021-02-08 19:59:22 ERROR (MainThread) [custom_components.awox.awox_mesh] Error fetching awox data: No device connected`

Model: Eglo ESpot 225

Edit: I'm running HA on docker.

**Comment by voxain** [comment]
@gstefanov Have you found a solution to this? I have been experiencing the same issue, I'm not sure what I'm doing wrong. @fsaris 

I'm running on CasaOS, so HA is inside of a docker container.

Executing the commands manually inside the container gives no errors: 
![image](https://user-images.githubusercontent.com/40141421/233698836-d70cb871-9bd9-4602-84fa-0954a42a1148.png)


```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.awox.scanner
Source: custom_components/awox/bluetoothctl.py:18
Integration: AwoX Mesh Beleuchtung (documentation, issues)
First occurred: 19:20:47 (12 occurrences)
Last logged: 19:26:33

Find devices process error: Command 'PATH=/usr/sbin:$PATH; rfkill unblock bluetooth' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/config/custom_components/awox/scanner.py", line 39, in async_find_devices
    bl = await hass.async_add_executor_job(init)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/awox/scanner.py", line 35, in init
    return Bluetoothctl()
  File "/config/custom_components/awox/bluetoothctl.py", line 18, in __init__
    subprocess.check_output("PATH=/usr/sbin:$PATH; rfkill unblock bluetooth", shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'PATH=/usr/sbin:$PATH; rfkill unblock bluetooth' returned non-zero exit status 1.
```

**Comment by gstefanov** [comment]
Hey, no, I moved away from eglo stuff or bluetooth in general. I'm sorry I can't help you.

**Comment by voxain** [comment]
@fsaris Would you be able to say something about this?

**Comment by fsaris** [comment]
No sorry, not sure what happens here.

I can recommend to switch to a dedicated esp32 device because currently the Bluetooth for devices that don't follow the BLE specs isn't working that great with HA. https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub
