### ISSUE TITLE
Lights stay offline

### ISSUE THREAD

**Issue by Wezze03** [fsaris/home-assistant-awox#73]
The lights stayed offline. I reinstalled the awox and found this error in logs:
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.awox.awox_mesh
Source: custom_components/awox/awoxmeshlight/__init__.py:202
Integration: AwoX MESH control (documentation, issues)
First occurred: 15:26:03 (1 occurrences)
Last logged: 15:26:03

exception
Traceback (most recent call last):
  File "/config/custom_components/awox/awox_mesh.py", line 324, in _async_connect_device
    if await self.hass.async_add_executor_job(device.connect):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 202, in connect
    self.btdevice.char_write(PAIR_CHAR_UUID, message)
  File "/usr/local/lib/python3.10/site-packages/pygatt/device.py", line 121, in char_write
    return self.char_write_handle(self.get_handle(uuid), value,
  File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/device.py", line 17, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/device.py", line 48, in char_write_handle
    self._backend.char_write_handle(self, handle, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py", line 49, in wrapper
    raise NotConnectedError()
pygatt.exceptions.NotConnectedError

Can someone help?

**Comment by fsaris** [comment]
Are you sure the light is in reach of your make sure the Bluetooth dongle. Enable debug logging (https://github.com/fsaris/home-assistant-awox/#troubleshooting) and check the RSSI values that are reported to validate the devices are in reach (check also https://www.home-assistant.io/integrations/bluetooth/#bluetooth-interference-with-other-devices)
