### ISSUE TITLE
Lights unavailable in home assistant 

### ISSUE THREAD

**Issue by Underctrl2020** [fsaris/home-assistant-awox#74]
Hi fsaris! 

First, I would like to thank you for your amazing work on this integration. I'm complete newbie to HA, so I hope I am not missing anything simple.

I have in total Awox 9 smart bulbs - four Eglo 12222 (ZigBee and BT) , one Eglo 12244 (ZigBee and BT) and five Eglo 11856 (BT only) . All these lights show properly in the Awox app and I can control them through there. 

I run HA on HA Blue, with attached Conbee stick and Asus BT adapter. I have 0.1.3 version of your Awox integration. 

All lights appear correctly in HA after installing the integration through HACS and entering my credentials, however all the five 5 Eglo 11856 bulbs appear as not available. I have tried to remove the integration and different versions, with the same outcome.

Going through the logs I found 4 errors and 3 warnings and I think the connection is timing out for the 5 BT bulbs. I have attached logs below for all the errors and warnings merged into txt file as I have not figured out how to copy the full log.  I do not understand why they appear as unavailable as I can control them through the Awox native app and they are all within reach of each other and also within reach of my home assistant.

What am I missing?

Thanks again for all the hard work invested into the integration & problem solving. 
underctrl

[Awox_logs.txt](https://github.com/fsaris/home-assistant-awox/files/10030284/Awox_logs.txt)

**Comment by Geranni** [comment]
I have the exact same issue with my:
- 5x EPanel_300, Version 2.2.17 (HW 4.30)
- 2x EPanel_600, Version 2.2.17 (HW 4.30)
- 1x EGLO-RGB-TW, Version 2.6.17 (HW 4.50)

Here is the log message:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.awox.awox_mesh
Source: custom_components/awox/awoxmeshlight/__init__.py:108
Integration: AwoX Mesh Beleuchtung (documentation, issues)
First occurred: 23:29:57 (27 occurrences)
Last logged: 23:37:31

exception Timed out connecting to a4:c1:38:a3:33:53 after 15 seconds.
exception Timed out connecting to a4:c1:38:a7:7c:7f after 15 seconds.
exception Timed out connecting to a4:c1:38:e4:0e:99 after 15 seconds.
exception Timed out connecting to a4:c1:38:ee:0c:67 after 15 seconds.
exception Timed out connecting to a4:c1:38:96:d9:18 after 15 seconds.
Traceback (most recent call last):
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 101, in connect
    with self._receiver.event("connect", timeout):
  File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/awox/awox_mesh.py", line 324, in _async_connect_device
    if await self.hass.async_add_executor_job(device.connect):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 196, in connect
    self.btdevice = self.adapter.connect(self.mac, timeout=15)
  File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 108, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to a4:c1:38:e4:0e:99 after 15 seconds.

**Comment by ludoComp9** [comment]
Exactly the same issue !
